version: '3.9'
services:
  api:
    build: ./server
    ports: ["5000:5000"]
    environment:
      - MONGO_URI=mongodb://mongo:27017/lms
      - JWT_SECRET=change-me
      - JWT_REFRESH_SECRET=change-me-too
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
    ports: ["27017:27017"]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
volumes:
  mongo-data:
