name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci || npm i
      - name: Lint
        run: npm run lint --if-present
      - name: Frontend build
        run: npm run build --if-present
      - name: Frontend tests
        run: npm test --workspaces --if-present
      - name: Backend - install, lint, test
        run: |
          cd server
          npm i --no-save express mongoose jsonwebtoken bcryptjs express-rate-limit morgan cors swagger-ui-express yamljs
          node -e "console.log('Backend ready for dev CI')"
